In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import scipy.stats as st
import numpy as np
from geopy.geocoders import Nominatim

In [2]:
!pip install geopy

Requirement already satisfied: geopy in c:\users\prern\anaconda3\lib\site-packages (2.3.0)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\prern\anaconda3\lib\site-packages (from geopy) (2.0)

In [3]:
# Initialize Nominatim API
geolocator = Nominatim(user_agent="MyApp")

In [4]:
df_diffdisorders  = pd.read_csv("Resources/prevalence-by-mental-and-substance-use-disorder.csv")

In [5]:
df_diffdisorders.head()

,Entity,Code,Year,Prevalence - Schizophrenia - Sex: Both - Age: Age-standardized (Percent),Prevalence - Bipolar disorder - Sex: Both - Age: Age-standardized (Percent),Prevalence - Eating disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Anxiety disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Drug use disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Depressive disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Alcohol use disorders - Sex: Both - Age: Age-standardized (Percent)
0,Afghanistan,AFG,1990,0.228979,0.721207,0.131001,4.835127,0.454202,5.125291,0.444036
1,Afghanistan,AFG,1991,0.228120,0.719952,0.126395,4.821765,0.447112,5.116306,0.444250
2,Afghanistan,AFG,1992,0.227328,0.718418,0.121832,4.801434,0.441190,5.106558,0.445501
3,Afghanistan,AFG,1993,0.226468,0.717452,0.117942,4.789363,0.435581,5.100328,0.445958
4,Afghanistan,AFG,1994,0.225567,0.717012,0.114547,4.784923,0.431822,5.099424,0.445779

In [6]:
def get_lat_lon(country):
    
    try:
        location = geolocator.geocode(country)
        return location.latitude, location.longitude
    except:
        return np.nan

In [7]:
countries = df_diffdisorders ["Entity"].unique()

In [8]:
countries_lat_lon = {}

for c in countries:
    print("country: ", c)
    countries_lat_lon[c] = get_lat_lon(c)

country:  Afghanistan
country:  African Region (WHO)
country:  Albania
country:  Algeria
country:  American Samoa
country:  Andorra
country:  Angola
country:  Antigua and Barbuda
country:  Argentina
country:  Armenia
country:  Australia
country:  Austria
country:  Azerbaijan
country:  Bahamas
country:  Bahrain
country:  Bangladesh
country:  Barbados
country:  Belarus
country:  Belgium
country:  Belize
country:  Benin
country:  Bermuda
country:  Bhutan
country:  Bolivia
country:  Bosnia and Herzegovina
country:  Botswana
country:  Brazil
country:  Brunei
country:  Bulgaria
country:  Burkina Faso
country:  Burundi
country:  Cambodia
country:  Cameroon
country:  Canada
country:  Cape Verde
country:  Central African Republic
country:  Chad
country:  Chile
country:  China
country:  Colombia
country:  Comoros
country:  Congo
country:  Cook Islands
country:  Costa Rica
country:  Cote d'Ivoire
country:  Croatia
country:  Cuba
country:  Cyprus
country:  Czechia
country:  Democratic Republic of Congo
country:  Denmark
country:  Djibouti
country:  Dominica
country:  Dominican Republic
country:  East Asia & Pacific (WB)
country:  Eastern Mediterranean Region (WHO)
country:  Ecuador
country:  Egypt
country:  El Salvador
country:  England
country:  Equatorial Guinea
country:  Eritrea
country:  Estonia
country:  Eswatini
country:  Ethiopia
country:  Europe & Central Asia (WB)
country:  European Region (WHO)
country:  Fiji
country:  Finland
country:  France
country:  G20
country:  Gabon
country:  Gambia
country:  Georgia
country:  Germany
country:  Ghana
country:  Greece
country:  Greenland
country:  Grenada
country:  Guam
country:  Guatemala
country:  Guinea
country:  Guinea-Bissau
country:  Guyana
country:  Haiti
country:  Honduras
country:  Hungary
country:  Iceland
country:  India
country:  Indonesia
country:  Iran
country:  Iraq
country:  Ireland
country:  Israel
country:  Italy
country:  Jamaica
country:  Japan
country:  Jordan
country:  Kazakhstan
country:  Kenya
country:  Kiribati
country:  Kuwait
country:  Kyrgyzstan
country:  Laos
country:  Latin America & Caribbean (WB)
country:  Latvia
country:  Lebanon
country:  Lesotho
country:  Liberia
country:  Libya
country:  Lithuania
country:  Luxembourg
country:  Madagascar
country:  Malawi
country:  Malaysia
country:  Maldives
country:  Mali
country:  Malta
country:  Marshall Islands
country:  Mauritania
country:  Mauritius
country:  Mexico
country:  Micronesia (country)
country:  Middle East & North Africa (WB)
country:  Moldova
country:  Monaco
country:  Mongolia
country:  Montenegro
country:  Morocco
country:  Mozambique
country:  Myanmar
country:  Namibia
country:  Nauru
country:  Nepal
country:  Netherlands
country:  New Zealand
country:  Nicaragua
country:  Niger
country:  Nigeria
country:  Niue
country:  North America (WB)
country:  North Korea
country:  North Macedonia
country:  Northern Ireland
country:  Northern Mariana Islands
country:  Norway
country:  OECD Countries
country:  Oman
country:  Pakistan
country:  Palau
country:  Palestine
country:  Panama
country:  Papua New Guinea
country:  Paraguay
country:  Peru
country:  Philippines
country:  Poland
country:  Portugal
country:  Puerto Rico
country:  Qatar
country:  Region of the Americas (WHO)
country:  Romania
country:  Russia
country:  Rwanda
country:  Saint Kitts and Nevis
country:  Saint Lucia
country:  Saint Vincent and the Grenadines
country:  Samoa
country:  San Marino
country:  Sao Tome and Principe
country:  Saudi Arabia
country:  Scotland
country:  Senegal
country:  Serbia
country:  Seychelles
country:  Sierra Leone
country:  Singapore
country:  Slovakia
country:  Slovenia
country:  Solomon Islands
country:  Somalia
country:  South Africa
country:  South Asia (WB)
country:  South Korea
country:  South Sudan
country:  South-East Asia Region (WHO)
country:  Spain
country:  Sri Lanka
country:  Sub-Saharan Africa (WB)
country:  Sudan
country:  Suriname
country:  Sweden
country:  Switzerland
country:  Syria
country:  Taiwan
country:  Tajikistan
country:  Tanzania
country:  Thailand
country:  Timor
country:  Togo
country:  Tokelau
country:  Tonga
country:  Trinidad and Tobago
country:  Tunisia
country:  Turkey
country:  Turkmenistan
country:  Tuvalu
country:  Uganda
country:  Ukraine
country:  United Arab Emirates
country:  United Kingdom
country:  United States
country:  United States Virgin Islands
country:  Uruguay
country:  Uzbekistan
country:  Vanuatu
country:  Venezuela
country:  Vietnam
country:  Wales
country:  Western Pacific Region (WHO)
country:  World
country:  World Bank High Income
country:  World Bank Low Income
country:  World Bank Lower Middle Income
country:  World Bank Upper Middle Income
country:  Yemen
country:  Zambia
country:  Zimbabwe

In [9]:
countries_lat_lon

{'Afghanistan': (33.7680065, 66.2385139),
 'African Region (WHO)': nan,
 'Albania': (41.000028, 19.9999619),
 'Algeria': (28.0000272, 2.9999825),
 'American Samoa': (-14.297124, -170.7131481),
 'Andorra': (42.5407167, 1.5732033),
 'Angola': (-11.8775768, 17.5691241),
 'Antigua and Barbuda': (17.2234721, -61.9554608),
 'Argentina': (-34.9964963, -64.9672817),
 'Armenia': (40.7696272, 44.6736646),
 'Australia': (-24.7761086, 134.755),
 'Austria': (47.59397, 14.12456),
 'Azerbaijan': (40.3936294, 47.7872508),
 'Bahamas': (24.7736546, -78.0000547),
 'Bahrain': (26.1551249, 50.5344606),
 'Bangladesh': (24.4769288, 90.2934413),
 'Barbados': (13.1500331, -59.5250305),
 'Belarus': (53.4250605, 27.6971358),
 'Belgium': (50.6402809, 4.6667145),
 'Belize': (16.8259793, -88.7600927),
 'Benin': (9.5293472, 2.2584408),
 'Bermuda': (32.30382, -64.7561647),
 'Bhutan': (27.549511, 90.5119273),
 'Bolivia': (-17.0568696, -64.9912286),
 'Bosnia and Herzegovina': (44.3053476, 17.5961467),
 'Botswana': (-23.1681782, 24.5928742),
 'Brazil': (-10.3333333, -53.2),
 'Brunei': (4.4137155, 114.5653908),
 'Bulgaria': (42.6073975, 25.4856617),
 'Burkina Faso': (12.0753083, -1.6880314),
 'Burundi': (-3.426449, 29.9324519),
 'Cambodia': (12.5433216, 104.8144914),
 'Cameroon': (4.6125522, 13.1535811),
 'Canada': (61.0666922, -107.991707),
 'Cape Verde': (16.0000552, -24.0083947),
 'Central African Republic': (7.0323598, 19.9981227),
 'Chad': (15.6134137, 19.0156172),
 'Chile': (-31.7613365, -71.3187697),
 'China': (35.000074, 104.999927),
 'Colombia': (4.099917, -72.9088133),
 'Comoros': (-12.2045176, 44.2832964),
 'Congo': (-2.9814344, 23.8222636),
 'Cook Islands': (-19.919672900000002, -157.9753368892878),
 'Costa Rica': (10.2735633, -84.0739102),
 "Cote d'Ivoire": (7.9897371, -5.5679458),
 'Croatia': (45.3658443, 15.6575209),
 'Cuba': (23.0131338, -80.8328748),
 'Cyprus': (34.9823018, 33.1451285),
 'Czechia': (49.7439047, 15.3381061),
 'Democratic Republic of Congo': (-15.4139213, 28.289698),
 'Denmark': (55.670249, 10.3333283),
 'Djibouti': (11.8145966, 42.8453061),
 'Dominica': (19.0974031, -70.3028026),
 'Dominican Republic': (19.0974031, -70.3028026),
 'East Asia & Pacific (WB)': nan,
 'Eastern Mediterranean Region (WHO)': nan,
 'Ecuador': (-1.3397668, -79.3666965),
 'Egypt': (26.2540493, 29.2675469),
 'El Salvador': (13.8000382, -88.9140683),
 'England': (52.5310214, -1.2649062),
 'Equatorial Guinea': (1.613172, 10.5170357),
 'Eritrea': (15.9500319, 37.9999668),
 'Estonia': (58.7523778, 25.3319078),
 'Eswatini': (-26.5624806, 31.3991317),
 'Ethiopia': (10.2116702, 38.6521203),
 'Europe & Central Asia (WB)': nan,
 'European Region (WHO)': nan,
 'Fiji': (-18.1239696, 179.0122737),
 'Finland': (63.2467777, 25.9209164),
 'France': (46.603354, 1.8883335),
 'G20': (36.8324966, 117.4384952),
 'Gabon': (-0.8999695, 11.6899699),
 'Gambia': (13.470062, -15.4900464),
 'Georgia': (32.3293809, -83.1137366),
 'Germany': (51.1638175, 10.4478313),
 'Ghana': (8.0300284, -1.0800271),
 'Greece': (38.9953683, 21.9877132),
 'Greenland': (77.6192349, -42.8125967),
 'Grenada': (12.1360374, -61.6904045),
 'Guam': (13.450125700000001, 144.75755102972062),
 'Guatemala': (15.5855545, -90.345759),
 'Guinea': (10.7226226, -10.7083587),
 'Guinea-Bissau': (11.815215, -15.2351044),
 'Guyana': (4.8417097, -58.6416891),
 'Haiti': (19.1399952, -72.3570972),
 'Honduras': (15.2572432, -86.0755145),
 'Hungary': (47.1817585, 19.5060937),
 'Iceland': (64.9841821, -18.1059013),
 'India': (22.3511148, 78.6677428),
 'Indonesia': (-2.4833826, 117.8902853),
 'Iran': (32.6475314, 54.5643516),
 'Iraq': (33.0955793, 44.1749775),
 'Ireland': (52.865196, -7.9794599),
 'Israel': (30.8124247, 34.8594762),
 'Italy': (42.6384261, 12.674297),
 'Jamaica': (18.1850507, -77.3947693),
 'Japan': (36.5748441, 139.2394179),
 'Jordan': (31.1667049, 36.941628),
 'Kazakhstan': (48.1012954, 66.7780818),
 'Kenya': (1.4419683, 38.4313975),
 'Kiribati': (0.3448612, 173.6641773),
 'Kuwait': (29.2733964, 47.4979476),
 'Kyrgyzstan': (41.5089324, 74.724091),
 'Laos': (20.0171109, 103.378253),
 'Latin America & Caribbean (WB)': nan,
 'Latvia': (56.8406494, 24.7537645),
 'Lebanon': (33.8750629, 35.843409),
 'Lesotho': (-29.6039267, 28.3350193),
 'Liberia': (5.7499721, -9.3658524),
 'Libya': (26.8234472, 18.1236723),
 'Lithuania': (55.3500003, 23.7499997),
 'Luxembourg': (49.8158683, 6.1296751),
 'Madagascar': (-18.9249604, 46.4416422),
 'Malawi': (-13.2687204, 33.9301963),
 'Malaysia': (4.5693754, 102.2656823),
 'Maldives': (3.7203503, 73.2244152),
 'Mali': (16.3700359, -2.2900239),
 'Malta': (35.8885993, 14.4476911),
 'Marshall Islands': (8.9995549, 168.0002575),
 'Mauritania': (20.2540382, -9.2399263),
 'Mauritius': (-20.2759451, 57.5703566),
 'Mexico': (23.6585116, -102.0077097),
 'Micronesia (country)': (14.3113868, 121.0698265),
 'Middle East & North Africa (WB)': nan,
 'Moldova': (47.2879608, 28.5670941),
 'Monaco': (43.7323492, 7.4276832),
 'Mongolia': (46.8250388, 103.8499736),
 'Montenegro': (42.9868853, 19.5180992),
 'Morocco': (31.1728205, -7.3362482),
 'Mozambique': (-19.302233, 34.9144977),
 'Myanmar': (17.1750495, 95.9999652),
 'Namibia': (-23.2335499, 17.3231107),
 'Nauru': (-0.5252306, 166.9324426),
 'Nepal': (28.1083929, 84.0917139),
 'Netherlands': (52.2434979, 5.6343227),
 'New Zealand': (-41.5000831, 172.8344077),
 'Nicaragua': (12.6090157, -85.2936911),
 'Niger': (17.7356214, 9.3238432),
 'Nigeria': (9.6000359, 7.9999721),
 'Niue': (-19.0536414, -169.861341),
 'North America (WB)': (39.8603439, -104.6904572),
 'North Korea': (40.3736611, 127.0870417),
 'North Macedonia': (41.6171214, 21.7168387),
 'Northern Ireland': (54.5859836, -6.9591554),
 'Northern Mariana Islands': (15.1753648, 145.7379338),
 'Norway': (61.1529386, 8.7876653),
 'OECD Countries': nan,
 'Oman': (21.0000287, 57.0036901),
 'Pakistan': (30.3308401, 71.247499),
 'Palau': (5.3783537, 132.9102573),
 'Palestine': (31.462420950000002, 34.262716572130714),
 'Panama': (8.559559, -81.1308434),
 'Papua New Guinea': (-5.6816069, 144.2489081),
 'Paraguay': (-23.3165935, -58.1693445),
 'Peru': (-6.8699697, -75.0458515),
 'Philippines': (12.7503486, 122.7312101),
 'Poland': (52.215933, 19.134422),
 'Portugal': (39.6621648, -8.1353519),
 'Puerto Rico': (18.2247706, -66.4858295),
 'Qatar': (25.3336984, 51.2295295),
 'Region of the Americas (WHO)': nan,
 'Romania': (45.9852129, 24.6859225),
 'Russia': (64.6863136, 97.7453061),
 'Rwanda': (-1.9646631, 30.0644358),
 'Saint Kitts and Nevis': (17.250512, -62.6725973),
 'Saint Lucia': (13.8250489, -60.975036),
 'Saint Vincent and the Grenadines': (12.90447, -61.2765569),
 'Samoa': (-13.7693895, -172.12005),
 'San Marino': (43.9458623, 12.458306),
 'Sao Tome and Principe': (0.9713095, 7.02255),
 'Saudi Arabia': (25.6242618, 42.3528328),
 'Scotland': (56.7861112, -4.1140518),
 'Senegal': (14.4750607, -14.4529612),
 'Serbia': (44.1534121, 20.55144),
 'Seychelles': (-4.6574977, 55.4540146),
 'Sierra Leone': (8.6400349, -11.8400269),
 'Singapore': (1.357107, 103.8194992),
 'Slovakia': (48.7411522, 19.4528646),
 'Slovenia': (46.1199444, 14.8153333),
 'Solomon Islands': (-8.7053941, 159.1070693851845),
 'Somalia': (8.3676771, 49.083416),
 'South Africa': (-28.8166236, 24.991639),
 'South Asia (WB)': (22.5728742, 88.433872),
 'South Korea': (36.638392, 127.6961188),
 'South Sudan': (7.8699431, 29.6667897),
 'South-East Asia Region (WHO)': nan,
 'Spain': (39.3260685, -4.8379791),
 'Sri Lanka': (7.877395849999999, 80.66247852355892),
 'Sub-Saharan Africa (WB)': nan,
 'Sudan': (14.5844444, 29.4917691),
 'Suriname': (4.1413025, -56.0771187),
 'Sweden': (59.6749712, 14.5208584),
 'Switzerland': (46.7985624, 8.2319736),
 'Syria': (34.6401861, 39.0494106),
 'Taiwan': (23.9739374, 120.9820179),
 'Tajikistan': (38.6281733, 70.8156541),
 'Tanzania': (-6.5247123, 35.7878438),
 'Thailand': (14.8971921, 100.83273),
 'Timor': (-9.346017100000001, 124.63707741045215),
 'Togo': (8.7800265, 1.0199765),
 'Tokelau': (-9.1676396, -171.819687),
 'Tonga': (-19.9160819, -175.202642),
 'Trinidad and Tobago': (10.7466905, -61.0840075),
 'Tunisia': (33.8439408, 9.400138),
 'Turkey': (38.9597594, 34.9249653),
 'Turkmenistan': (39.3763807, 59.3924609),
 'Tuvalu': (-8.6405212, 179.1582918181797),
 'Uganda': (1.5333554, 32.2166578),
 'Ukraine': (49.4871968, 31.2718321),
 'United Arab Emirates': (24.0002488, 53.9994829),
 'United Kingdom': (54.7023545, -3.2765753),
 'United States': (39.7837304, -100.445882),
 'United States Virgin Islands': (17.789187, -64.7080574),
 'Uruguay': (-32.8755548, -56.0201525),
 'Uzbekistan': (41.32373, 63.9528098),
 'Vanuatu': (-16.5255069, 168.1069154),
 'Venezuela': (8.0018709, -66.1109318),
 'Vietnam': (15.9266657, 107.9650855),
 'Wales': (52.2928116, -3.73893),
 'Western Pacific Region (WHO)': nan,
 'World': (-36.8535712, 174.7456809),
 'World Bank High Income': nan,
 'World Bank Low Income': nan,
 'World Bank Lower Middle Income': nan,
 'World Bank Upper Middle Income': nan,
 'Yemen': (16.3471243, 47.8915271),
 'Zambia': (-14.5189121, 27.5589884),
 'Zimbabwe': (-18.4554963, 29.7468414)}

# 2nd CSV file

In [10]:
df_diffdisorders["lat_lon"] = df_diffdisorders["Entity"].map(countries_lat_lon)

In [11]:
df_diffdisorders.head(2)

,Entity,Code,Year,Prevalence - Schizophrenia - Sex: Both - Age: Age-standardized (Percent),Prevalence - Bipolar disorder - Sex: Both - Age: Age-standardized (Percent),Prevalence - Eating disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Anxiety disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Drug use disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Depressive disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Alcohol use disorders - Sex: Both - Age: Age-standardized (Percent),lat_lon
0,Afghanistan,AFG,1990,0.228979,0.721207,0.131001,4.835127,0.454202,5.125291,0.444036,"(33.7680065, 66.2385139)"
1,Afghanistan,AFG,1991,0.228120,0.719952,0.126395,4.821765,0.447112,5.116306,0.444250,"(33.7680065, 66.2385139)"

In [12]:
discard_indexes = df_diffdisorders[df_diffdisorders["lat_lon"].isnull()].index
df_diffdisorders = df_diffdisorders.drop(discard_indexes)

In [13]:
df_diffdisorders.head(2)

,Entity,Code,Year,Prevalence - Schizophrenia - Sex: Both - Age: Age-standardized (Percent),Prevalence - Bipolar disorder - Sex: Both - Age: Age-standardized (Percent),Prevalence - Eating disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Anxiety disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Drug use disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Depressive disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Alcohol use disorders - Sex: Both - Age: Age-standardized (Percent),lat_lon
0,Afghanistan,AFG,1990,0.228979,0.721207,0.131001,4.835127,0.454202,5.125291,0.444036,"(33.7680065, 66.2385139)"
1,Afghanistan,AFG,1991,0.228120,0.719952,0.126395,4.821765,0.447112,5.116306,0.444250,"(33.7680065, 66.2385139)"

In [14]:
df_diffdisorders["latitude"] = df_diffdisorders["lat_lon"].map(lambda x: x[0])
df_diffdisorders["longitude"] = df_diffdisorders["lat_lon"].map(lambda x: x[1])

In [15]:
df_diffdisorders

,Entity,Code,Year,Prevalence - Schizophrenia - Sex: Both - Age: Age-standardized (Percent),Prevalence - Bipolar disorder - Sex: Both - Age: Age-standardized (Percent),Prevalence - Eating disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Anxiety disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Drug use disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Depressive disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Alcohol use disorders - Sex: Both - Age: Age-standardized (Percent),lat_lon,latitude,longitude
0,Afghanistan,AFG,1990,0.228979,0.721207,0.131001,4.835127,0.454202,5.125291,0.444036,"(33.7680065, 66.2385139)",33.768006,66.238514
1,Afghanistan,AFG,1991,0.228120,0.719952,0.126395,4.821765,0.447112,5.116306,0.444250,"(33.7680065, 66.2385139)",33.768006,66.238514
2,Afghanistan,AFG,1992,0.227328,0.718418,0.121832,4.801434,0.441190,5.106558,0.445501,"(33.7680065, 66.2385139)",33.768006,66.238514
3,Afghanistan,AFG,1993,0.226468,0.717452,0.117942,4.789363,0.435581,5.100328,0.445958,"(33.7680065, 66.2385139)",33.768006,66.238514
4,Afghanistan,AFG,1994,0.225567,0.717012,0.114547,4.784923,0.431822,5.099424,0.445779,"(33.7680065, 66.2385139)",33.768006,66.238514
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6835,Zimbabwe,ZWE,2015,0.209359,0.560882,0.099610,3.315701,0.599604,3.548613,1.734969,"(-18.4554963, 29.7468414)",-18.455496,29.746841
6836,Zimbabwe,ZWE,2016,0.209979,0.561768,0.100821,3.324230,0.603658,3.557508,1.689281,"(-18.4554963, 29.7468414)",-18.455496,29.746841
6837,Zimbabwe,ZWE,2017,0.210631,0.562612,0.101671,3.330569,0.608096,3.564138,1.651805,"(-18.4554963, 29.7468414)",-18.455496,29.746841
6838,Zimbabwe,ZWE,2018,0.211237,0.563283,0.102398,3.317500,0.609065,3.563141,1.686711,"(-18.4554963, 29.7468414)",-18.455496,29.746841
6839,Zimbabwe,ZWE,2019,0.211969,0.563820,0.102902,3.283934,0.610644,3.554571,1.776729,"(-18.4554963, 29.7468414)",-18.455496,29.746841

In [16]:
df_diffdisorders = df_diffdisorders.drop('lat_lon', axis=1)

In [17]:
df_diffdisorders.head(2)

,Entity,Code,Year,Prevalence - Schizophrenia - Sex: Both - Age: Age-standardized (Percent),Prevalence - Bipolar disorder - Sex: Both - Age: Age-standardized (Percent),Prevalence - Eating disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Anxiety disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Drug use disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Depressive disorders - Sex: Both - Age: Age-standardized (Percent),Prevalence - Alcohol use disorders - Sex: Both - Age: Age-standardized (Percent),latitude,longitude
0,Afghanistan,AFG,1990,0.228979,0.721207,0.131001,4.835127,0.454202,5.125291,0.444036,33.768006,66.238514
1,Afghanistan,AFG,1991,0.228120,0.719952,0.126395,4.821765,0.447112,5.116306,0.444250,33.768006,66.238514

In [23]:
df_diffdisorders = df_diffdisorders.rename(columns = {
'Prevalence - Schizophrenia - Sex: Both - Age: Age-standardized (Percent)':'Schizophrenia',
'Prevalence - Bipolar disorder - Sex: Both - Age: Age-standardized (Percent)':'Bipolar_disorder',  
'Prevalence - Eating disorders - Sex: Both - Age: Age-standardized (Percent)':'Eating_disorder',                                                  
'Prevalence - Anxiety disorders - Sex: Both - Age: Age-standardized (Percent)':'Anxiety',
'Prevalence - Drug use disorders - Sex: Both - Age: Age-standardized (Percent)':'Drug_usage',
'Prevalence - Depressive disorders - Sex: Both - Age: Age-standardized (Percent)':'Depression',
'Prevalence - Alcohol use disorders - Sex: Both - Age: Age-standardized (Percent)':'Alcohol'})

In [24]:
df_diffdisorders.drop('Code',axis=1,inplace=True)

,Entity,Code,Year,Schizophrenia,Bipolar_disorder,Eating_disorders,Anxiety_disorders,Drug_use_disorders,Depressive_disorders,Alcohol_use_disorders,latitude,longitude
0,Afghanistan,AFG,1990,0.228979,0.721207,0.131001,4.835127,0.454202,5.125291,0.444036,33.768006,66.238514
1,Afghanistan,AFG,1991,0.228120,0.719952,0.126395,4.821765,0.447112,5.116306,0.444250,33.768006,66.238514
2,Afghanistan,AFG,1992,0.227328,0.718418,0.121832,4.801434,0.441190,5.106558,0.445501,33.768006,66.238514
3,Afghanistan,AFG,1993,0.226468,0.717452,0.117942,4.789363,0.435581,5.100328,0.445958,33.768006,66.238514
4,Afghanistan,AFG,1994,0.225567,0.717012,0.114547,4.784923,0.431822,5.099424,0.445779,33.768006,66.238514
...,...,...,...,...,...,...,...,...,...,...,...,...
6835,Zimbabwe,ZWE,2015,0.209359,0.560882,0.099610,3.315701,0.599604,3.548613,1.734969,-18.455496,29.746841
6836,Zimbabwe,ZWE,2016,0.209979,0.561768,0.100821,3.324230,0.603658,3.557508,1.689281,-18.455496,29.746841
6837,Zimbabwe,ZWE,2017,0.210631,0.562612,0.101671,3.330569,0.608096,3.564138,1.651805,-18.455496,29.746841
6838,Zimbabwe,ZWE,2018,0.211237,0.563283,0.102398,3.317500,0.609065,3.563141,1.686711,-18.455496,29.746841
6839,Zimbabwe,ZWE,2019,0.211969,0.563820,0.102902,3.283934,0.610644,3.554571,1.776729,-18.455496,29.746841

In [26]:
df_diffdisorders

,Entity,Year,Schizophrenia,Bipolar_disorder,Eating_disorders,Anxiety_disorders,Drug_use_disorders,Depressive_disorders,Alcohol_use_disorders,latitude,longitude
0,Afghanistan,1990,0.228979,0.721207,0.131001,4.835127,0.454202,5.125291,0.444036,33.768006,66.238514
1,Afghanistan,1991,0.228120,0.719952,0.126395,4.821765,0.447112,5.116306,0.444250,33.768006,66.238514
2,Afghanistan,1992,0.227328,0.718418,0.121832,4.801434,0.441190,5.106558,0.445501,33.768006,66.238514
3,Afghanistan,1993,0.226468,0.717452,0.117942,4.789363,0.435581,5.100328,0.445958,33.768006,66.238514
4,Afghanistan,1994,0.225567,0.717012,0.114547,4.784923,0.431822,5.099424,0.445779,33.768006,66.238514
...,...,...,...,...,...,...,...,...,...,...,...
6835,Zimbabwe,2015,0.209359,0.560882,0.099610,3.315701,0.599604,3.548613,1.734969,-18.455496,29.746841
6836,Zimbabwe,2016,0.209979,0.561768,0.100821,3.324230,0.603658,3.557508,1.689281,-18.455496,29.746841
6837,Zimbabwe,2017,0.210631,0.562612,0.101671,3.330569,0.608096,3.564138,1.651805,-18.455496,29.746841
6838,Zimbabwe,2018,0.211237,0.563283,0.102398,3.317500,0.609065,3.563141,1.686711,-18.455496,29.746841
6839,Zimbabwe,2019,0.211969,0.563820,0.102902,3.283934,0.610644,3.554571,1.776729,-18.455496,29.746841

In [27]:
df_diffdisorders.to_csv('Clean_data/df_diffdisorders.csv', index=False)

In [28]:
df_diffdisorders.isnull().sum()

Entity                   0
Year                     0
Schizophrenia            0
Bipolar_disorder         0
Eating_disorders         0
Anxiety_disorders        0
Drug_use_disorders       0
Depressive_disorders     0
Alcohol_use_disorders    0
latitude                 0
longitude                0
dtype: int64